---
format_version: 10
environments:
  internal:
    pipelines:
      - gocd-trial-launcher
      - gocd-trial-installers
      - gocd-trial-installers-stable
pipelines:
  gocd-trial-launcher:
    group: go-cd-contrib
    display_order: -5
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
        destination: launcher
      codesigning:
        git: https://github.com/gocd/codesigning
        destination: codesigning
    environment_variables:
      RELEASE: 1.0.0
    stages:
      - build:
          elastic_profile_id: ecs-golang-build
          tasks:
            - script: launcher/build.sh --verbose --prod && mv launcher/dist .
          artifacts:
            - build:
                source: dist/**/*
                destination: dist/
      - code-signing:
          clean_workspace: yes
          secure_variables:
            GOCD_GPG_PASSPHRASE: "AES:7lAutKoRKMuSnh3Sbg9DeQ==:8fhND9w/8AWw6dJhmWpTcCdKSsEcOzriQNiKFZD6XtN+sJvZ65NH/QFXRNiy192+SSTKsbhOrFmw+kAKt5+MH1Erd6H54zJjpSgvJUmsJaQ="
          jobs:
            win:
              elastic_profile_id: ecs-gocd-dev-build
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: dist/
                - script: cd codesigning && rake --trace win:metadata_single_binary[../dist/windows/amd64/run-gocd.exe,../win-launcher.zip]
              artifacts:
                - build:
                    source: win-launcher.zip
      - bundle:
          elastic_profile_id: ecs-golang-build
          tasks:
            - fetch:
                stage: build
                job: build
                source: dist/
            - fetch:
                stage: code-signing
                job: win
                source: win-launcher.zip
                is_file: yes
            - script: |
                set -eux
                echo "Collating code-signed binaries..."
                (cd dist/windows/amd64 && unzip -o ../../../win-launcher.zip)
                sha256sum dist/darwin/amd64/run-gocd
                sha256sum dist/darwin/arm64/run-gocd
                sha256sum dist/linux/amd64/run-gocd
                sha256sum dist/windows/amd64/run-gocd.exe
                zip -r launchers.zip dist
          artifacts:
            - build:
                source: launchers.zip
  gocd-trial-installers:
    group: go-cd
    display_order: 5
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
      launcher:
        pipeline: gocd-trial-launcher
        stage: bundle
      regression: # Only build new installers every time main regression tests pass
        pipeline: regression-SPAs
        stage: Firefox
    environment_variables:
      GOCD_UPLOAD_S3_BUCKET: downloadgocdio-downloadgocdios3-192sau789jtkh
    stages:
      - package:
          elastic_profile_id: ecs-gocd-dev-build
          tasks:
            - fetch:
                pipeline: installers/smoke/regression-SPAs
                stage: dist
                job: dist
                source: dist/zip/
                destination: deps/
            - fetch:
                pipeline: gocd-trial-launcher
                stage: bundle
                job: bundle
                source: launchers.zip
                is_file: yes
            - script: |
                set -eux
                unzip -o launchers.zip
                cd assembly/config
                bundle
                bundle exec rake
            - script: ./assembly/package.sh osx osx-aarch64 linux windows
          artifacts:
            - build:
                source: installers/*
                destination: installers/
      - upload:
          elastic_profile_id: ecs-gocd-dev-build-release-aws-privileged
          tasks:
            - fetch:
                stage: package
                job: package
                source: installers
            - script: ruby assembly/upload.rb installers
  gocd-trial-installers-stable:
    group: go-cd
    display_order: 5
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
      trial-installers: # Only release installers for each stable release off the same dependent code
        pipeline: gocd-trial-installers
        stage: upload
      publish-stable: # Only release installers for each stable release off the same dependent code
        pipeline: PublishStableRelease
        stage: promote-binaries
    environment_variables:
      GOCD_UPLOAD_S3_BUCKET: downloadgocdio-downloadgocdios3-192sau789jtkh
    stages:
      - promote-to-stable:
          elastic_profile_id: ecs-gocd-dev-build-release-aws-privileged
          tasks:
            - fetch:
                pipeline: gocd-trial-installers
                stage: package
                job: package
                source: installers
            - script: ruby assembly/upload.rb --release installers
