---
format_version: 10
environments:
  internal:
    pipelines:
      - gocd-trial-launcher
      - gocd-trial-installers
      - gocd-trial-installers-stable
pipelines:
  gocd-trial-launcher:
    group: go-cd-contrib
    display_order: -5
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
        destination: launcher
    environment_variables:
      RELEASE: 1.0.0
    stages:
      - build:
          elastic_profile_id: ecs-golang-build
          tasks:
            - script: launcher/build.sh --verbose --prod && mv launcher/dist .
            - script: |
                set -eux
                echo "Collating binaries..."
                sha256sum dist/darwin/amd64/run-gocd
                sha256sum dist/darwin/arm64/run-gocd
                sha256sum dist/linux/amd64/run-gocd
                sha256sum dist/windows/amd64/run-gocd.exe
                zip -r launchers.zip dist
          artifacts:
            - build:
                source: launchers.zip
  gocd-trial-installers:
    group: go-cd
    display_order: 5
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
      launcher:
        pipeline: gocd-trial-launcher
        stage: build
      regression: # Only build new installers every time main regression tests pass
        pipeline: regression-SPAs
        stage: Firefox
    environment_variables:
      GOCD_UPLOAD_S3_BUCKET: downloadgocdio-downloadgocdios3-192sau789jtkh
    stages:
      - package:
          elastic_profile_id: ecs-gocd-dev-build
          tasks:
            - fetch:
                pipeline: installers/smoke/regression-SPAs
                stage: dist
                job: dist
                source: dist/zip/
                destination: deps/
            - fetch:
                pipeline: gocd-trial-launcher
                stage: build
                job: build
                source: launchers.zip
                is_file: yes
            - script: |
                set -eux
                unzip -o launchers.zip
                cd assembly/config
                bundle
                bundle exec rake
            - script: ./assembly/package.sh osx osx-aarch64 linux windows
          artifacts:
            - build:
                source: installers/*
                destination: installers/
      - upload:
          elastic_profile_id: ecs-gocd-dev-build-release-aws-privileged
          tasks:
            - fetch:
                stage: package
                job: package
                source: installers
            - script: ruby assembly/upload.rb installers
  gocd-trial-installers-stable:
    group: go-cd
    display_order: 5
    materials:
      github:
        git: https://git.gocd.io/git/gocd-contrib/gocd-trial-launcher
      trial-installers: # Only release installers for each stable release off the same dependent code
        pipeline: gocd-trial-installers
        stage: upload
      publish-stable: # Only release installers for each stable release off the same dependent code
        pipeline: PublishStableRelease
        stage: promote-binaries
    environment_variables:
      GOCD_UPLOAD_S3_BUCKET: downloadgocdio-downloadgocdios3-192sau789jtkh
    stages:
      - promote-to-stable:
          elastic_profile_id: ecs-gocd-dev-build-release-aws-privileged
          tasks:
            - fetch:
                pipeline: gocd-trial-installers
                stage: package
                job: package
                source: installers
            - script: ruby assembly/upload.rb --release installers
